### ISSUE TITLE
検索時エラーの見直し

### ISSUE THREAD

**Issue by biva8710** [s06181110/imageSearch#17]
見つけたバグ

- [x] 以上を選択してる時に人数書かなくても出てくる

- [x] からの時、１つ目のみを入力するとエラー文でない

**Comment by biva8710** [comment]
２個目は直しておきました

**Comment by uedaakira** [comment]
numberがnullであっても処理が行われてるからif(!$_POST['number']==null){を追加したら出てこなくなったけど無理矢理すぎるかな

**Comment by biva8710** [comment]
今リファクタリングしてるのでちょっとまってね

**Comment by biva8710** [comment]
これで言ってる部分直ってる？
ちなみに下のやつまだリファクタリングできるから見つけれたらやってみてね
https://github.com/s06181110/imageSearch/pull/18

**Comment by uedaakira** [comment]
直ってない~
なんかphpではnullは0と同値らしい
http://blog.katty.in/51

**Comment by biva8710** [comment]
これは以上の方の話か,
`===` にしたら区別されるってなってるけどそっちは？

**Comment by biva8710** [comment]
エラー発生を防ぐ方法のところに書いてあったわ
https://qiita.com/mpyw/items/2f9955db1c02eeef43ea

ここにも同じようなこと書いてある（こっちの方が見やすいかも）
http://manaminmemo.sblo.jp/article/72490577.html

できたけど一応やってもらうことにするわ、頑張って👍

**Comment by biva8710** [comment]
新しい作業の時はブランチ変えて〜
