### ISSUE TITLE
キーワードの部分一致

### ISSUE THREAD

**Issue by biva8710** [s06181110/imageSearch#5]

**Comment by frmtr** [comment]
grep_match()でやろうとしてるけど、$pattern　に$_POST使えんのやけど、どうしたらいいですか？
もしくは方針自体間違ってます？

preg_match ( string $pattern , string $subject [, array &$matches [, int $flags = 0 [, int $offset = 0 ]]] ) : int

**Comment by biva8710** [comment]
```php
preg_match('/$_POST[]/', ~)
```
だと、$_POSTと言う文字列をパターンマッチすることになる。
やし、なんとかして ` / で囲まれた$_POSTの文字列 ` を作ってやれば良い

**Comment by biva8710** [comment]
おれゆってることこう言うことやけど試した？
ちゃんとできたで
![スクリーンショット 2019-07-13 15 48 26](https://user-images.githubusercontent.com/27798778/61168223-c1131f00-a585-11e9-8530-7b270d5d085b.png)
